// <auto-generated />
using System;
using DragonQuestNine.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DragonQuestNine.Migrations
{
    [DbContext(typeof(DragonQuestDbContext))]
    [Migration("20210613153543_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DragonQuestNine.Models.Accolade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccoladeCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateObtained")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsObtained")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccoladeCategoryId");

                    b.ToTable("Accolades");
                });

            modelBuilder.Entity("DragonQuestNine.Models.AccoladeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccoladeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccoladeTypeId");

                    b.ToTable("AccoladeCategory");
                });

            modelBuilder.Entity("DragonQuestNine.Models.AccoladeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AccoladeType");
                });

            modelBuilder.Entity("DragonQuestNine.Models.Accolade", b =>
                {
                    b.HasOne("DragonQuestNine.Models.AccoladeCategory", "AccoladeCategory")
                        .WithMany()
                        .HasForeignKey("AccoladeCategoryId");

                    b.Navigation("AccoladeCategory");
                });

            modelBuilder.Entity("DragonQuestNine.Models.AccoladeCategory", b =>
                {
                    b.HasOne("DragonQuestNine.Models.AccoladeType", "AccoladeType")
                        .WithMany()
                        .HasForeignKey("AccoladeTypeId");

                    b.Navigation("AccoladeType");
                });
#pragma warning restore 612, 618
        }
    }
}
